### ISSUE TITLE
TypeError: this.options.format is not a function

### ISSUE THREAD

**Issue by blueyestar** [VeliovGroup/Meteor-logger-file#11]
### I'm having an issue:
I changed the file name format without changing the format, as following, but get a  this.options.format is not a function error. If I remove the fileNameFormat function, everything OK.
```
 const log = new Logger();
(new LoggerFile(log, {
  fileNameFormat(time) {
    return `${time.getFullYear()}-${time.getMonth() + 1}-${time.getDate()}.log`;
  },
  path: '/private/logs/',
})).enable({
  filter: ['ERROR', 'FATAL', 'WARN'],
});
```

```
W20180101-11:11:29.446(-5)? (STDERR) packages\meteor.js:1254
W20180101-11:11:29.450(-5)? (STDERR)     Fiber(runWithEnvironment).run();
W20180101-11:11:29.455(-5)? (STDERR)                               ^
W20180101-11:11:29.470(-5)? (STDERR)
W20180101-11:11:29.471(-5)? (STDERR) TypeError: this.options.format is not a function
W20180101-11:11:29.472(-5)? (STDERR)     at Object.LoggerFile.logger.add [as emitter] (packages/ostrio:loggerfile/server.js:118:95)
W20180101-11:11:29.474(-5)? (STDERR)     at Logger._log (packages/ostrio:logger/logger.js:64:31)
W20180101-11:11:29.475(-5)? (STDERR)     at Logger.error (packages/ostrio:logger/logger.js:198:17)
W20180101-11:11:29.476(-5)? (STDERR)     at Object.Meteor._debug (imports/startup/server/log.js:27:7)
W20180101-11:11:29.477(-5)? (STDERR)     at onException (packages\meteor.js:1222:14)
W20180101-11:11:29.479(-5)? (STDERR)     at runWithEnvironment (packages\meteor.js:1245:9)
```

  - ostrio:loggerfile 2.0.3
  - Meteor 1.6

**Comment by dr-dimitru** [comment]
Hello @blueyestar ,

Great you've just found a bug!
Thank you for reporting about it.
Should be fixed on [`v2.0.4`](https://github.com/VeliovGroup/Meteor-logger-file/releases/tag/2.0.4), please let me know if it is solved on your end.

**Comment by blueyestar** [comment]
@dr-dimitru 
Thank you for your work.
This bug is gone.

**Comment by dr-dimitru** [comment]
Hello @blueyestar ,

I'm glad issue is solved, thank you for reporting about this.
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
