### ISSUE TITLE
Error invoking Method '1_logger_emit_File': Method not found [404]

### ISSUE THREAD

**Issue by dedgar1** [VeliovGroup/Meteor-logger-file#12]
I implemented loggerfile on the client side as such

```
import { Logger } from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
const log1 = new Logger();
const log2 = new Logger();

(new LoggerFile(log2, {
    fileNameFormat(time) {
      return (time.getDate()) + "-" + (time.getMonth() + 1) + "-" + (time.getFullYear()) + "_" + (time.getHours()) + ".log";
    },
    format(time, level, message, data, userId) {
      return "[" + level + "] | " + (time.getMinutes()) + ":" + (time.getSeconds()) + " | \"" + message + "\" | User: " + userId + "\r\n";
    },
    path: 'logs/'
  })).enable();
  
log2.info('testing log 2');
```
On running the program, I get the error stated in the title. Below is an image of the error
![capture](https://user-images.githubusercontent.com/5598267/34490390-bb61230c-efad-11e7-8b18-648e0b6be6d7.PNG)

Any ideas what might be causing the issue?

**Comment by dr-dimitru** [comment]
Hello @dedgar1 ,

As you have stated:

> I implemented loggerfile on the client side

Note: Logger and LoggerFile must be initiated "isomorphically" (*at both, Server and Client*).

Please update this thread following our issue template:

  - Version of `ostrio:loggerfile` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Is it *Server* or *Client* (*Browser*) issue?
  - Browser name and its version (Chrome, Firefox, Safari, etc.)?
  - Platform name and its version (Win, Mac, Linux)?

**Comment by dedgar1** [comment]
- loggerfile versin 2.0.4
- meteor version 1.4
- Client Side issue on Chrome
-Linux OS

**Comment by dedgar1** [comment]
I found the solution  [here](https://github.com/VeliovGroup/Meteor-logger-console/issues/6)
@dr-dimitru, you mentioned that the following statements should be found on both the client and server side
```
const mylog = new Logger();
(new LoggerConsole(mylog)).enable();
```

**Comment by dr-dimitru** [comment]
I've mentioned that as well [above](https://github.com/VeliovGroup/Meteor-logger-file/issues/12#issuecomment-354810679):

> Note: Logger and LoggerFile must be initiated "isomorphically" (at both, Server and Client).

Feel free to close it in case if the issue is solved on your end.

**Comment by dedgar1** [comment]
True, I missed that.
Thanks for the help

**Comment by dr-dimitru** [comment]
@dedgar1 I'm glad it's solved 🎉

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
