### ISSUE TITLE
Option to disable automatic stringify for data object

### ISSUE THREAD

**Issue by Mairu** [VeliovGroup/Meteor-logger-file#14]
### I have a suggestion:
  - options to disable JSON.stringify of data before given to format function
  - I want to compose my own json to log or use data as options object for formatting options

**Comment by dr-dimitru** [comment]
Hello @Mairu ,

I believe this can be accomplished by using `format` function passed as option to *LoggerFile*.
`data` (*second argument*) is available in a `format` function as well.

Let me know wdyt, if you need a help to implement it, drop your current code here with more info on what exactly you're trying to accomplish.

`data` shouldn't be stringifyed, what function/setup do you use for actual data logging? Anyways even if it's stringifyed you can always do `JSON.parse(...)`

**Comment by Mairu** [comment]
> I believe this can be accomplished by using format function passed as option to LoggerFile.

That's exactly what I wanted to do, but the function get data as string instead of object.

data is stringified before the call of format https://github.com/VeliovGroup/Meteor-logger-file/blob/376b524afc537d31d089bee3689b2283acfcbb91/server.js#L110-L118

For now I do the JSON.parse and later on another JSON.stringify but this feels not good :worried:

For BC reasons I would propose an option to turn off the stringification.
If you don't want to change it, I have to live with it. I would also create a pull request.

**Comment by dr-dimitru** [comment]
Sure we had to do `stringify` here as you will end up with `[Object object]` in a file.
Doing `parse`/`stringify` looks totally fine here to me.

But I would accept PR with this feature, please make sure to follow [our guidelines](https://github.com/VeliovGroup/Meteor-logger-file/blob/master/.github/PULL_REQUEST_TEMPLATE).

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
