### ISSUE TITLE
How to do log rotation?

### ISSUE THREAD

**Issue by bhanuprasad04** [VeliovGroup/Meteor-logger-file#15]
To keep logs persistent during development  using absolute path outside of my project folder, everything working fine. now I want to keep only last 7 days log files. Is there any way to do this?

**Comment by dr-dimitru** [comment]
Hey @bhanuprasad04 ,

Do you mean "log rotation"?
So you want to keep logs only for 7 last days, right?

**Comment by bhanuprasad04** [comment]
yes.can you please help me

**Comment by dr-dimitru** [comment]
Hey @bhanuprasad04 sorry for the late reply.

You should update [`fileNameFormat`](https://github.com/VeliovGroup/Meteor-logger-file#example-2) option to make log files created daily. Then use [scheduled daily task](https://github.com/VeliovGroup/Meteor-CRON-jobs#cron-jobs-for-meteor) where you remove a file with name of the day seven days ago (-7):

```js
import { Logger }     from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
import { CRONjob }    from 'meteor/ostrio:cron-jobs';

const db   = Meteor.users.rawDatabase();
const cron = new CRONjob({db: db});

const LogFile = new LoggerFile(log, {
  fileNameFormat(time) {
    // Create log-files daily
    return (time.getDate()) + "-" + (time.getMonth() + 1) + "-" + (time.getFullYear()) + ".log";
  },
  path: '/data/logs/' // Use absolute storage path
});

const logRotate = function (ready) {
  const today = +new Date();
  const sevenDaysAgo = today - (1000 * 60 * 60 * 24 * 7);
  const etaMinus7 = new Date(sevenDaysAgo);
  const fileToRemove = (etaMinus7.getDate()) + "-" + (etaMinus7.getMonth() + 1) + "-" + (etaMinus7.getFullYear()) + ".log";

  fs.unlinkSync('/data/logs/' + fileToRemove);
  ready();
};

cron.logRotate(logRotate, 24 * 60 * 60 * 1000, 'logRotate');
```

Let me know if this works for you.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
