### ISSUE TITLE
When setting log file path I see Match error: Unknown key in field path

### ISSUE THREAD

**Issue by tomachinz** [VeliovGroup/Meteor-logger-file#16]
Using the code
```
// in a module:

if (Meteor.isServer) {
  (new LoggerFile(log)).enable({
    path: 'log/crowdcourier/cc.log'
  });
}

```
I'm trying to see the log file path to either:
log/crowdcourier/cc.log (inside my app)
/var/log/crowdcourier/cc.log (in the os folder, after chown/chgrp/chmod/touch)

Not sure the version of `ostrio:loggerfile` but after breaking my app with "meteor update" I stopped doing that and am on:
ostrio:logger@2.0.5
ostrio:loggerconsole@2.0.3
ostrio:loggerfile@2.0.3
ostrio:loggermongo@2.0.3
ostrio:meteor-root@1.0.6

Is that bad? OK I'm gonna focus on upgrades... 

  - Version of `Meteor` meteor@1.8.2
  - server issue
  - chrome etc
  - dev on macOS 10.12.6 run on linux ubuntu Linux cc192 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

stack trace

W20180921-00:53:20.466(12)? (STDERR) /Users/tom/.meteor/packages/meteor-tool/.1.6.0_1.1bjh68e.79zm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180921-00:53:20.467(12)? (STDERR) 						throw(ex);
W20180921-00:53:20.468(12)? (STDERR) 						^
W20180921-00:53:20.468(12)? (STDERR) Error: Match error: Unknown key in field path
W20180921-00:53:20.469(12)? (STDERR)     at exports.check (packages/check.js:55:15)
W20180921-00:53:20.469(12)? (STDERR)     at LoggerFile.enable (packages/ostrio:loggerfile/server.js:123:5)
W20180921-00:53:20.470(12)? (STDERR)     at crowd-courier-tools.js (imports/modules/crowd-courier-tools.js:226:25)
W20180921-00:53:20.470(12)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180921-00:53:20.470(12)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180921-00:53:20.471(12)? (STDERR)     at on-create-user.js (imports/startup/server/accounts/on-create-user.js:1:241)
W20180921-00:53:20.471(12)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180921-00:53:20.471(12)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180921-00:53:20.471(12)? (STDERR)     at index.js (imports/startup/server/accounts/index.js:1:90)
W20180921-00:53:20.557(12)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
=> Exited with code: 1

# Meteor packages used by this project
meteor-base@1.2.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.3.1                   # The database Meteor supports right now
reactive-var            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.9.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.0            # Server-side component of the `meteor shell` command

accounts-base@1.4.0
accounts-password@1.5.0
aldeed:collection2-core@2.0.1
audit-argument-checks@1.0.7
alanning:roles
fourseven:scss
twbs:bootstrap
service-configuration@1.0.11
accounts-facebook@1.3.0
accounts-github@1.4.0
accounts-google@1.3.0
themeteorchef:bert
fortawesome:fontawesome
ddp-rate-limiter@1.0.7
dynamic-import@0.2.0
static-html
browser-policy@1.1.0
meteortoys:allthings
ostrio:logger
ostrio:loggerfile
ejson@1.1.0
ostrio:loggermongo
ostrio:loggerconsole
dburles:google-maps
react-template-helper
react-meteor-data

http

**Comment by dr-dimitru** [comment]
Hello @tomachinz ,

You should pass settings as second argument of `new LoggerFile`, but you'r passing it to `.enable` method, change your code to:
```js
if (Meteor.isServer) {
  (new LoggerFile(log, {
    path: 'log/crowdcourier/cc.log'
  })).enable();
}
```

**Comment by tomachinz** [comment]
Thanks dude! You are all that is awesome about open source.

**Comment by dr-dimitru** [comment]
@tomachinz I'm glad it's solved in the easy way.
Feel free to reopen it in case if the issue is still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
