### ISSUE TITLE
Frontend errors

### ISSUE THREAD

**Issue by Deadly0** [VeliovGroup/Meteor-logger-file#2]
`Uncaught TypeError: Meteor.userId is not a function ostrio:logger.coffee:7`
`Uncaught TypeError: Cannot read property 'add' of undefined ostrio:loggerfile.coffee:4`

That errors appeared in browser console after I have installed this package.

**Comment by dr-dimitru** [comment]
@Deadly0 even without calling `Meteor.log...`?
Also could you please paste code of the `Meteor.log.rule()` and output of `meteor list`?

**Comment by Deadly0** [comment]
This happened right after I have installed the package. I didn't call any Meteor.log methods.
P.S. My platform is Windows, maybe that because of it.

`meteor list`

coffeescript              1.0.6  Javascript dialect with fewer braces and semicolons
cryptoquick:stylus-multi  1.2.1  Stylus, packaged with Nib, Jeet, Rupture, and Axis
d3js:d3                   3.5.5  D3 (official): A JavaScript visualization library for HTML and SVG.
http                      1.1.0  Make HTTP calls to remote servers
insecure                  1.0.3  Allow all database writes by default
iron:router               1.0.7  Routing specifically designed for Meteor
jquery                    1.11.3_2  Manipulate the DOM using CSS selectors
meteor-platform           1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:unblock       1.1.0  a way to use this.unblock inside publications
momentjs:moment           2.10.3  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mrt:cron                  0.0.1  Simple meteor.cron
mrt:moment-timezone       0.2.1  Timezone support for moment.js, packaged for Meteor. See http://momentjs.com/timezone.
ostrio:logger             0.0.5  Meteor isomorphic logger driver
ostrio:loggerfile         0.0.8  Simply store application logs into file within ostrio:logger package
raix:handlebar-helpers    0.2.4  Handlebar helpers

**Comment by dr-dimitru** [comment]
@Deadly0 Got it, update will be published in 20 mins

**Comment by Deadly0** [comment]
@dr-dimitru, thank you!

**Comment by dr-dimitru** [comment]
@Deadly0 fixed in 1b47ebd407bf8eed52d49fa4c861a1efd892d1df , please update the driver via `meteor update` command

**Comment by Deadly0** [comment]
@dr-dimitru, thank you again, fixed!

**Comment by dr-dimitru** [comment]
@Deadly0 You're very welcome, thank you for reporting about this issue, and testing on your end.
