### ISSUE TITLE
Where to find the log file?

### ISSUE THREAD

**Issue by wangfenjin** [VeliovGroup/Meteor-logger-file#3]
I have a silly question, where can I find the log file. I can't find any file in my project dir after use this package.

Thanks.

**Comment by dr-dimitru** [comment]
Hi @WangFenjin 
on dev stage: `/static/logs`
on prod stage: `/assets/app/logs`
more [here](https://github.com/VeliovGroup/Meteor-logger-file/blob/master/loggerfile.coffee#L24)

You can easily set another path via `Meteor.log.file.format`, like:

``` javascript
Meteor.log.file.path = '/another/path';
```

**Comment by dr-dimitru** [comment]
Hi @WangFenjin ,
Is this issue solved?

**Comment by wangfenjin** [comment]
Hi @dr-dimitru ,
Sorry for late response.

No, there is even no folder named /static/logs or /assets/app/logs in my host. And I look into the code, seems no where create the folder.

**Comment by dr-dimitru** [comment]
[Here](https://github.com/VeliovGroup/Meteor-logger-file/blob/master/loggerfile.coffee#L14) and [here](https://github.com/VeliovGroup/Meteor-logger-file/blob/master/loggerfile.coffee#L38) file and directory will be created if not exists. (P.S. I'm using `fs-extra` npm package)

Could you add to server this line and post here its output?:

``` javascript
Meteor.startup(function() {
  console.log("Meteor.log.file.path", Meteor.log.file.path);
});
```

**Comment by wangfenjin** [comment]
Hi @dr-dimitru ,

Thanks for your response. I tried again, and set Meteor.log.file.path to my home folder, the log file appears now. Seems it can't create folder under /static/logs or /assets/app/logs in OSX. 

You can close this issue now, Thanks.

**Comment by dr-dimitru** [comment]
Depends from which folder you are running Meteor and its permissions

**Comment by jerradpatch** [comment]
Why doesn't meteor just put its logs for global installation under 'var/log/meteor', just like other Linux applications? Or is '/static/logs or /assets/app/logs' a well known location for NPM installs that I was unaware of?

**Comment by dr-dimitru** [comment]
Hello @jerradpatch ,

There is so many Linux implementations, also we have a Mac and Windows, - there is no silver bullet to fit them all.

Default path is chosen to meet Meteor's needs, without breaking its functionality.

For every case it's highly recommended to set `path` option to meet your needs:
```js
new LoggerFile(LoggerInstance, {
  path: '/var/log/meteor'
});
```
