### ISSUE TITLE
Logs are not working in Meteor.startup()

### ISSUE THREAD

**Issue by sakshi-kataria** [VeliovGroup/Meteor-logger-file#5]
Logs are not working in Meteor.startUp() function

**Comment by dr-dimitru** [comment]
Hi @sakshi-kataria ,

I guess is a typo, there is no `Meteor.startUp()`, but `Meteor.startup()`, right?

**Comment by sakshi-kataria** [comment]
yes right..

**Comment by dr-dimitru** [comment]
Can we close it now?

**Comment by sakshi-kataria** [comment]
but why it is not working in this package.. in my project i want to do it
I write   Meteor.startup(function () {
but here typing mistake

**Comment by sakshi-kataria** [comment]
``` js
  Meteor.startup(function () {
    var logPath = "E:/SmartBox_Admin/Smartbox";
// Initialize Logger

    this.log = new Logger();
    console.log('this.log', this.log );
// Initialize LoggerFile:
    var LogFile = new LoggerFile(log, {
      fileNameFormat: function(time) {
        /* Create log-files hourly */
        return (time.getDate()) + "-" + (time.getMonth() + 1) + "-" + (time.getFullYear()) + ".log";
      },
      format: function(time, level, message, data, userId) {
        var date = new Date();
        var ip='';
        Meteor.call('getIP', function(error, result){
          if(error){
            console.log(error);
          }
          else {
            ip=result;
          }
        });
        var dtDate=date.getDate() +"/" +  date.getMonth()+"/"+date.getFullYear()+" " + (time.getHours()) + ":"  + (time.getMinutes()) + ":" + (time.getSeconds())+ "." +(time.getMilliseconds());
        var user=Meteor.users.findOne(userId);
        if (user!==undefined){
          return "[" + level + "] " + dtDate + " HostName:"+ ip +", Message:" + message + ", User:" + user.emails[0].address + "\r\n";
        }
        else {
          return "";
        }
        /* Omit Date and hours from messages */
      },
      path: logPath /* Use absolute storage path */
    });


// Enable LoggerFile with default settings
    LogFile.enable();
    console.log('LogFile', LogFile );
     log.info('1');
}
```

**Comment by sakshi-kataria** [comment]
to enable log i tried this as well

``` js
// Enable LoggerFile with default settings
LogFile.enable({enable: true,
  filter: ['ERROR', 'FATAL', 'WARN', 'DEBUG', 'INFO', 'TRACE'], /* Filters: 'ERROR', 'FATAL', 'WARN', 'DEBUG', 'INFO', 'TRACE', '*' */
  client: true, /* This allows to call, and execute on Client */
  server: true });
```

but still not working

**Comment by dr-dimitru** [comment]
1. Does it work from other places in code?
2. Try to use all default settings `this.log = new Logger(); (new LoggerFile(log)).enable();` in this case is logs written?
3. Are you getting any errors?
4. Note: _I never has a chance to test it on Windows_

**Comment by sakshi-kataria** [comment]
1. yes it is working in another code .. I tried only in client side
2. yes at log.info "method not found" error is coming
3. if i will Try default settings this.log = new Logger(); (new LoggerFile(log)).enable();
   where logs will go i need to check it on my log file

**Comment by dr-dimitru** [comment]
1. Could you please try Server side?
2. Which method? Could you post full error stack?
3. Default path:
   - On `dev`: `.meteor/local/build/programs/server/static/logs`  (_relative to meteor project directory_)
   - On `prod`: `assets/app/logs` (_relative to running directory_)

**Comment by dr-dimitru** [comment]
Hi @sakshi-kataria 
Is this issue still persists?

**Comment by dr-dimitru** [comment]
@sakshi-kataria  ?

**Comment by sakshi-kataria** [comment]
It has been resolved
