### ISSUE TITLE
Error invoking Method '1_logger_emit_File': Method not found [404]

### ISSUE THREAD

**Issue by sonu-kumar1** [VeliovGroup/Meteor-logger-file#6]
hello , I am trying this package on My application but found some error. can you resolve it
**Error: Error invoking Method '1_logger_emit_File': Method not found [404]**

**Comment by sonu-kumar1** [comment]
One more thing i am using meteor application by grunt means desktop application

**Comment by dr-dimitru** [comment]
I guess you're missing the server side. This package requires it.

**Comment by sonu-kumar1** [comment]
i am not able to understand ,what you want to say. 

actually we are using 2 application in our company
in 1 web application it is working but in another  desktop application is not working. can you please help me ...

**Comment by dr-dimitru** [comment]
Is you desktop app has connection to server? Or it's standalone?

**Comment by sonu-kumar1** [comment]
yes,  desktop app has connection to server

**Comment by dr-dimitru** [comment]
Hi @sonu-kumar1 ,
Sorry for silence on my end.
1. Is this issue still persist?
2. What if you call method right form Browser's console? `Meteor.call('1_logger_emit_File', function (){ console.log(arguments); })`

**Comment by dr-dimitru** [comment]
@sonu-kumar1 any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to no response on topic-starter end

**Comment by dedgar1** [comment]
![capture](https://user-images.githubusercontent.com/5598267/34489680-42977cde-efab-11e7-8ab1-53bbc1ed8cbd.PNG)

That's the result from performing the call @dr-dimitru stated above. Can I get help with this?

**Comment by dr-dimitru** [comment]
Hello @dedgar1 ,

Please create a new issue following our [issue template](https://github.com/VeliovGroup/Meteor-logger-file/blob/master/.github/ISSUE_TEMPLATE).
