### ISSUE TITLE
Not able to use load Function on Windows, it works perfectly fine on Ubuntu LTS 14

### ISSUE THREAD

**Issue by salmanhasni** [VeliovGroup/Meteor-logger-file#7]
This is the error
W20160813-01:37:37.669(5)? (STDERR) stream.js:74
W20160813-01:37:37.724(5)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20160813-01:37:37.724(5)? (STDERR)       ^
W20160813-01:37:37.724(5)? (STDERR) 
W20160813-01:37:37.724(5)? (STDERR) Error: ENOENT: no such file or directory, open 'E:\wcif.meteor\local\build\programs\server\assets\app\uploads\Images\Hc42Pg6kigDj9PpSh.jpg?oh=36b427001c86a63a8b53819e99aa7000&oe=584DDFBE&__gda__=1478129990_b368aeadf01e50a998b8c20c9270fd0b'
W20160813-01:37:37.725(5)? (STDERR)     at Error (native)

here is my code

**Shared Code**

```
this.Images = new FilesCollection({
    collectionName: 'Images',
    allowClientCode: false, // Disallow remove files from Client
    onBeforeUpload: function (file) {
        // Allow upload files under 10MB, and only in png/jpg/jpeg formats
        if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
            file.uploadedAt = new Date();
            return true;
        } else {
            return 'Please upload image, with size equal or less than 10MB';
        }
    }
});
```

**Server Code**

```
var getQuestionImage = function(url, questionId){
    if(url){
        Images.load(url, {
            meta : {
                questionId: questionId
            }
        });
    }
};

Meteor.startup(function(){
    if(Meteor.settings.allowScrapping) {
        getQuestionImage (<dont bother this, parameters having no issues>);
    }
});
```

**Comment by dr-dimitru** [comment]
1. `?oh=36b427001c86a63a8b53819e99aa7000&oe=584DDFBE&gda=1478129990_b368aeadf01e50a998b8c20c9270fd0b` Where those parameters comes from?
2. Why you're posting question related to _Meteor-Files_ to _loggerfile_ repository? Or am I missing something?

**Comment by salmanhasni** [comment]
@dr-dimitru Sorry Open wrong tab, let me post it there

**Comment by dr-dimitru** [comment]
👍 and answer on the first question please :)

**Comment by salmanhasni** [comment]
@dr-dimitru I have posted the question in the Meteor files repo can you please ask it there
