### ISSUE TITLE
How to import into MeteorJS file?

### ISSUE THREAD

**Issue by scheung38** [VeliovGroup/Meteor-logger-file#8]
var Logger = require('logger')

or 

var Logger = require('Logger')

before actual usage?

**Comment by dr-dimitru** [comment]
``` jsx
import { Logger } from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
```

**Comment by scheung38** [comment]
logger file <- with or without space thank

**Comment by dr-dimitru** [comment]
> logger file <- with or without space thank

Without, _damn spellcheck_

**Comment by scheung38** [comment]
So I would simply place it inside Meteor.startUp({ ...... ?

**Comment by dr-dimitru** [comment]
IDK, up to you.
But if you're not using ES6, you don;t need to require it - its already in global scope

**Comment by scheung38** [comment]
I only want to log whenever there is HTTP connection error, say whenever it is down, not authorized, etc or else the messages will be too much. How to do that thanks

```
Meteor.startup(() => {

import {Logger} from 'meteor/ostrio:logger';
import {LoggerFile} from 'meteor/ostrio:loggerfile';

this.log = new Logger();
console.log('this.log is : ', this.log);
```

Why is the above causing build error:

Syntax error: Unexpected reserved word pointing at import?

**Comment by dr-dimitru** [comment]
It's all up to you depends for your logic, here is good example from docs:

``` js
/* Store original window.onerror */
var _WoE = window.onerror;

window.onerror = function(msg, url, line) {
  log.error(msg, {file: url, onLine: line});
  if (_WoE) {
    _WoE.apply(this, arguments);
  }
};
```

**Comment by scheung38** [comment]
could you show example, server side, such that whenever there is HTTP connectivity then logs

**Comment by dr-dimitru** [comment]
1. For HTTP use middleware, package `webapp`, `WebApp.connectHandlers.use()`
2. For DDP use `Meteor.onConnection()`, see https://docs.meteor.com/api/connections.html#Meteor-onConnection

Sorry but this is already out of the scope of this package

**Comment by scheung38** [comment]
Thanks so what type of logging is this package for, thanks

**Comment by dr-dimitru** [comment]
Any, server or client
You define where and what to log in your app's code
