### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by marcusmalloc** [VeliovGroup/Meteor-logger-file#9]
There is an issue in IE 11 when using ostrio:loggerfile on the client side.

Steps to reproduce:

1) meteor create testapp
2) cd testapp
3) meteor add ostrio:logger ostrio:loggerfile
3) add imports to client/main.js

```
import { Logger }     from 'meteor/ostrio:logger';
import { LoggerFile } from 'meteor/ostrio:loggerfile';
```

Once the application is started, there is an error in IE

> Syntax error
> File: ostrio_loggerfile.js, Line: 313, Column: 51

The problem is that there is an arrow function there

[https://github.com/jprichardson/node-fs-extra/blob/master/lib/util/assign.js#L5](https://github.com/jprichardson/node-fs-extra/blob/master/lib/util/assign.js#L5)

I think this is the same issue as in

[https://github.com/VeliovGroup/Meteor-Files/issues/445](https://github.com/VeliovGroup/Meteor-Files/issues/445)

and explained in

[https://github.com/VeliovGroup/Meteor-Files/issues/445#issuecomment-307674362](https://github.com/VeliovGroup/Meteor-Files/issues/445#issuecomment-307674362)

Thank you

**Comment by dr-dimitru** [comment]
Hello @mddarko ,

Thank you for reporting this. Fixed in [`v2.0.1`](https://github.com/VeliovGroup/Meteor-logger-file/releases/tag/2.0.1)

Let me know how it works for you

**Comment by marcusmalloc** [comment]
Great, it works!

Thank you

**Comment by dr-dimitru** [comment]
@mddarko awesome :)
Thank you once again for reporting about this.
